#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

variables:
    GIT_STRATEGY: none

# The configuration of the build is split over multiple files to more clearly
# arrange the different configurations. The included files are supposed to
# expose hidden keys that can be extended.
# NOTE: gitlab doesn't support recursive includes yet, so we flatten everything
# here

checkout:
    image: stellargroup/build_env:ubuntu
    stage: checkout
    variables:
        GIT_STRATEGY: fetch
        GIT_DEPTH: "1"
    script:
        # Moving checked out files to seperate directory ...
        - cd ..
        - mv hpx tmp
        - mkdir hpx
        - mv tmp hpx/source;
        - cp hpx/source/.clang-tidy hpx/
    artifacts:
        paths:
            - source

include:
    - .gitlab-ci/stages.yml
    - .gitlab-ci/cmake.yml
    - .gitlab-ci/inspect.yml
    - .gitlab-ci/core.yml
    - .gitlab-ci/test.yml
    - .gitlab-ci/docker.yml
    - .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/debug.yml
    - .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/debug-asan.yml
    - .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/debug-ubsan.yml
    - .gitlab-ci/linux/x86/clang-7.0.1/boost-1.65.1/release.yml
    - .gitlab-ci/docs.yml
