#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Run inspect on a given source tree
.inspect:
    image: stellargroup/build_env:ubuntu
    stage: build
    script:
        - cd build
        - ninja inspect
        - touch hpx-no-inspect
        - cd ../source
        - ./build/bin/inspect --all --output=./hpx_inspect_report.html .
    after_script:
        - ./source/tools/inspect/inspect_to_junit.py ./hpx_inspect_report.html ./hpx_inspect.xml
    artifacts:
        when: on_failure
        paths:
            - hpx_inspect_report.html
            - build
        reports:
            junit: hpx_inspect.xml
    except:
        - gh-pages
