#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

.debug-x86: &debug-x86
    variables:
        CMAKE_BUILD_TYPE: "Debug"
        CMAKE_EXTRA_FLAGS: "-DCMAKE_CXX_CLANG_TIDY=clang-tidy"
        TARGET_IMAGE_NAME: stellargroup/hpx:dev
    tags:
        - linux
        - x86
        - clang-7.0.1
        - boost-1.65.1

cmake Debug x86:
    <<: *debug-x86
    extends: .cmake

inspect Debug x86:
    <<: *debug-x86
    extends: .inspect
    dependencies:
        - cmake Debug x86

core Debug x86:
    <<: *debug-x86
    extends: .core
    dependencies:
        - cmake Debug x86

examples Debug x86:
    <<: *debug-x86
    variables:
        TESTS: "examples"
    extends: .test
    dependencies:
        - core Debug x86
        - get conv.xsl
        - get junit2html
    artifacts:
        paths:
            - build

tests.unit Debug x86:
    <<: *debug-x86
    variables:
        TESTS: "tests.unit"
    extends: .test
    dependencies:
        - core Debug x86
        - get conv.xsl
        - get junit2html

tests.regressions Debug x86:
    <<: *debug-x86
    variables:
        TESTS: "tests.regressions"
    extends: .test
    dependencies:
        - core Debug x86
        - get conv.xsl
        - get junit2html

tests.performance Debug x86:
    <<: *debug-x86
    variables:
        TESTS: "tests.performance"
    extends: .test
    dependencies:
        - core Debug x86
        - get conv.xsl
        - get junit2html

tests.headers Debug x86:
    <<: *debug-x86
    variables:
        TESTS: "tests.headers"
    extends: .test
    dependencies:
        - core Debug x86
        - get conv.xsl
        - get junit2html

docker Debug x86:
    <<: *debug-x86
    extends: .docker
    environment:
        name: dev/docker_images
        url: https://hub.docker.com/r/stellargroup/hpx/tags
    dependencies:
        - core Debug x86
        - inspect Debug x86
        - examples Debug x86
        - build docs
