# Copyright (c) 2026 The STE||AR Group
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Documentation Build

on:
  push

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    container: stellargroup/build_env:17

    steps:
    - uses: actions/checkout@v6
    - name: Configure
      shell: bash
      run: |
          cmake \
              -Bbuild \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DHPX_WITH_MALLOC=system \
              -DHPX_WITH_FETCH_ASIO=ON \
              -DHPX_WITH_EXAMPLES=ON \
              -DHPX_WITH_TESTS=OFF \
              -DHPX_WITH_DOCUMENTATION=ON \
              -DHPX_WITH_DOCUMENTATION_OUTPUT_FORMATS="html;singlehtml;latexpdf" \

    - name: Build Documentation (HTML)
      shell: bash
      run: cmake --build build --target docs-html

    - name: Build Documentation (Single HTML)
      shell: bash
      run: cmake --build build --target docs-singlehtml

    - name: Build Documentation (PDF)
      shell: bash
      run: cmake --build build --target docs-latexpdf

    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: documentation-artifacts
        path: |
          build/share/hpx/docs/html
          build/share/hpx/docs/singlehtml
          build/share/hpx/docs/latexpdf/latex/HPX.pdf

    - name: Configure Local Git
      shell: bash
      run: |
          git config --global user.name "StellarBot"
          git config --global user.email "contact@stellar-group.org"

    - name: Push Documentation
      if: github.ref == 'refs/heads/master'
      shell: bash
      run: |
        cmake --build build --target git_docs
