# Copyright (c) 2020 Mikael Simberg
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Windows CI (Release)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        md C:\projects
        $client = new-object System.Net.WebClient
        $client.DownloadFile("https://rostam.cct.lsu.edu/download/builder/vcpkg-export-hpx-dependencies.7z","C:\projects\vcpkg-export-hpx-dependencies.7z")
        7z x C:\projects\vcpkg-export-hpx-dependencies.7z -y -oC:\projects\vcpkg
    - name: Configure
      shell: bash
      run: |
          cmake . -Bbuild -G'Visual Studio 16 2019' \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE='C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake' \
              -DHPX_WITH_PSEUDO_DEPENDENCIES=OFF \
              -DHPX_WITH_EXAMPLES=ON \
              -DHPX_WITH_TESTS=ON \
              -DHPX_WITH_TESTS_UNIT=ON \
              -DHPX_WITH_DEPRECATION_WARNINGS=OFF \
              -DHPX_WITH_TESTS_MAX_THREADS_PER_LOCALITY=2 \
              -DHPX_WITH_CHECK_MODULE_DEPENDENCIES=On
    - name: Build
      shell: bash
      run: |
          cmake --build build --config Release \
          --target ALL_BUILD \
            cmake_build_dir_targets_test.make_compile \
            cmake_build_dir_macros_test.make_compile \
          -- -maxcpucount -verbosity:minimal -nologo
    - name: Install
      shell: bash
      run: |
          cmake --install build
    - name: Build External
      shell: bash
      run: |
          cmake --build build --config Release \
            --target cmake_install_dir_targets_test.make_compile \
              cmake_install_dir_macros_test.make_compile \
            -- -maxcpucount -verbosity:minimal -nologo
    - name: Test
      shell: bash
      run: |
          cd build
          ctest \
          --output-on-failure \
            --build-config Release \
            --tests-regex tests.examples \
            --exclude-regex \
          "tests.examples.1d_stencil.1d_stencil_6|\
          tests.examples.1d_stencil.1d_stencil_7|\
          tests.examples.async_io.async_io_simple|\
          tests.examples.modules.checkpoint.1d_stencil_4_checkpoint|\
          tests.examples.modules.program_options.config_file_types|\
          tests.examples.modules.program_options.custom_syntax|\
          tests.examples.modules.program_options.env_options|\
          tests.examples.modules.program_options.first|\
          tests.examples.modules.program_options.multiple_sources|\
          tests.examples.modules.program_options.option_groups|\
          tests.examples.modules.program_options.options_description|\
          tests.examples.modules.program_options.options_hierarchy|\
          tests.examples.modules.program_options.real|\
          tests.examples.modules.program_options.regex|\
          tests.examples.modules.program_options.response_file|\
          tests.examples.modules.resiliency_distributed.distributed.tcp.async_replay_distributed|\
          tests.examples.modules.resiliency_distributed.distributed.tcp.async_replicate_distributed|\
          tests.examples.modules.resiliency.1d_stencil_replay_exception|\
          tests.examples.modules.resiliency.1d_stencil_replay_validate|\
          tests.examples.modules.resiliency.async_replay|\
          tests.examples.modules.resiliency.async_replicate_vote|\
          tests.examples.modules.resiliency.async_replicate|\
          tests.examples.modules.resiliency.dataflow_replicate|\
          tests.examples.modules.resiliency.version|\
          tests.examples.modules.resource_partitioner.async_customization|\
          tests.examples.modules.resource_partitioner.guided_pool_test|\
          tests.examples.modules.resource_partitioner.oversubscribing_resource_partitioner|\
          tests.examples.modules.resource_partitioner.simple_resource_partitioner|\
          tests.examples.modules.resource_partitioner.simplest_resource_partitioner_1|\
          tests.examples.modules.resource_partitioner.simplest_resource_partitioner_2|\
          tests.examples.quickstart.1d_wave_equation|\
          tests.examples.quickstart.partitioned_vector_spmd_foreach|\
          tests.examples.quickstart.sort_by_key_demo|\
          tests.examples.thread_aware_timer.thread_aware_timer|\
          tests.examples.transpose.transpose_block_numa"
